### ISSUE TITLE
UI of current master branch has over sized command box and top bar

### ISSUE THREAD

**Issue by potatowagon** [CS2103AUG2016-T11-C4/main#180]
![screenshot 61](https://cloud.githubusercontent.com/assets/19604232/20037561/ec4f7218-a45c-11e6-848f-1d05abbcb03b.png)

**Comment by pyokagan** [comment]
@potatowagon What kind of size do you want?

Anyway you can adjust it to your liking in the `DarkTheme.css` file:

``` css
#commandTextField {
    -fx-font-size: 20pt;
    -fx-padding: 1em;
}
```
